imports:
    - { resource: '../src/*Bundle/Resources/config/services.yaml' }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false