services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\MainBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    App\MainBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
